"""Create an interactive time-based HTML report."""
import argparse, json
from pathlib import Path
import numpy as np

def main():
    p=argparse.ArgumentParser(); p.add_argument("data",type=Path); p.add_argument("--output",type=Path,required=True); p.add_argument("--video",default=""); a=p.parse_args()
    d=np.load(a.data,allow_pickle=True); names=d["joint_names"].astype(str).tolist(); payload={k:d[k].tolist() for k in ("time","torque","velocity","power","contact")}; payload["joint_names"]=names
    e=float(d.get("total_energy",np.nan)); dist=float(d.get("total_distance",np.nan)); dur=float(d.get("measurement_duration",10)); mass=5.424414725; cot=e/(mass*9.81*dist) if dist>0 else float("nan")
    html=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Cheetah report</title><script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script><style>body{{font-family:Arial;margin:24px;background:#f3f5f7}}section{{background:#fff;padding:18px;margin:12px 0;border-radius:10px}}button{{padding:10px 16px;margin:3px;border:0;border-radius:6px}}button.active{{background:#1769aa;color:#fff}}.tab{{display:none}}.tab.active{{display:block}}.chart{{height:360px;margin:12px 0}}</style></head><body><h1>Робот-гепард с гибкой спиной</h1><section>Масса: <b>{mass:.6f} кг</b> · Приводов: <b>{len(names)}</b> · Измерение: <b>{dur:.1f} с</b><br>Энергия: <b>{e:.3f} Дж</b> · Дистанция: <b>{dist:.3f} м</b> · CoT: <b>{cot:.6f}</b></section>'''
    if a.video: html+=f'<section><h2>Видео</h2><video controls style="max-width:900px" src="{a.video}"></video></section>'
    html+='<section><div id="buttons"></div><div id="tabs"></div></section><script>const D='+json.dumps(payload)+r''';const tabs={};function show(n){Object.values(tabs).forEach(s=>s.classList.remove('active'));tabs[n].classList.add('active');document.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.textContent===n))}function add(n,k,u){let b=document.createElement('button');b.textContent=n;b.onclick=()=>show(n);buttons.appendChild(b);let s=document.createElement('div');s.className='tab';tabs[n]=s;tabsDiv.appendChild(s);if(k==='flight'){s.innerHTML='<div class="chart" id="flight"></div>';let y=D.contact.map(r=>r.reduce((a,b)=>a+b,0)===0?1:0);Plotly.newPlot('flight',[{x:D.time,y,name:'flight',mode:'lines'}],{title:'Фазы полёта',xaxis:{title:'Время, с'},yaxis:{title:'Полёт (1) / контакт (0)'}})}else{D.joint_names.forEach((name,i)=>{let id=n+i;s.insertAdjacentHTML('beforeend','<h3>'+name+'</h3><div class="chart" id="'+id+'"></div>');Plotly.newPlot(id,[{x:D.time,y:D[k].map(r=>r[i]),name:name,mode:'lines'}],{title:n+' — '+name,xaxis:{title:'Время, с'},yaxis:{title:u}})})}}let tabsDiv=document.getElementById('tabs');add('Энергия','power','Мощность, Вт');add('Угловые скорости приводов','velocity','рад/с');add('Моменты приводов','torque','Н·м');add('Фазы полёта','flight','');show('Энергия');</script></body></html>'''
    a.output.write_text(html,encoding='utf-8'); print('Saved:',a.output)
if __name__=='__main__': main()
